### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by leyuan-sun** [ybgdgh/FSE-ROS#1]
Hi

**Comment by rginjapan** [comment]
@ybgdgh Thanks a lot for this repo. I have investigated a little bit, I think this repo could help me a lot for real robot experiments. However, I have some questions in the code:
1. what is the /map used for and where does it come from, https://github.com/ybgdgh/FSE-ROS/blob/942e25dd153da174b01a456772d43fb26ddcc61c/fsp_node/scripts/fsp_node.py#L131C1-L132C1
2. what is this topic /use_map_topic, https://github.com/ybgdgh/FSE-ROS/blob/942e25dd153da174b01a456772d43fb26ddcc61c/fsp_node/launch/fsp_node.launch#L3C2-L3C46

Looking forward to your reply.
